name: Deploy Backend to Azure Container Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_NAME: vacapp-backend
  IMAGE_TAG: v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout del código
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Login a Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3. Login al Azure Container Registry
    - name: Login to Azure Container Registry
      run: az acr login --name acrvacapp

    # 4. Build y Push de la imagen Docker
    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    # 5. Deploy a Container Apps (solo en main)
    - name: Deploy to Azure Container Apps
      if: github.ref == 'refs/heads/main'
      run: |
        az containerapp update \
          --name ${{ secrets.CONTAINER_APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    # 6. Verificar deployment
    - name: Verify deployment
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deployment completed!"
        echo "API URL: https://ca-vacapp-api.calmsmoke-a4ab58e7.eastus2.azurecontainerapps.io"
        echo "New feature: Permisos automáticos para jefes implementados"